# Generated by Django 4.2.8 on 2023-12-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_bhm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Truck', 'Yuk mashina'), ('Light car', 'Yelgil mashina')], default='Light car', max_length=20),
        ),
    ]
