# Generated by Django 4.2.8 on 2023-12-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_dat_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.TimeField(),
        ),
    ]
